type: 'robot'
queue_size: 5
max_size: 3
utility:
  expression: 'distance skill'
  distance: 0.4
skills:
  size: 7
  skill0:
    resource: 'camera'
    type: 0
    utility:
      skill: 0.4
  skill1:
    resource: 'battery'
    type: 2
    level: 0.7
    utility:
      skill: 1.8
  skill2:
    resource: 'processor'
    type: 1
    level: 3
    utility:
      skill: 3.2
  skill3:
    resource: 'laserscan'
    type: 0
    utility:
      skill: 0.9
  skill4:
    resource: 'strengh'
    type: 2
    level: 6.6
    utility:
      skill: 3.4
  skill5:
    resource: 'mobile'
    type: 0
    utility:
      skill: 2.8
  skill6:
    resource: 'holonomic'
    type: 0
    utility:
      skill: 20.0
