type: 'robot'
queue_size: 10
max_size: 2
utility:
  expression: 'distance feature'
  distance: 1.2
features:
  size: 7
  feature0:
    resource: 'camera'
    type: 0
    utility:
      feature: 1.0
  feature1:
    resource: 'battery'
    type: 2
    level: 0.85
    utility:
      feature: 1.0
  feature2:
    resource: 'processor'
    type: 1
    level: 1
    utility:
      feature: 2
  feature3:
    resource: 'laserscan'
    type: 0
    utility:
      feature: 0.4
  feature4:
    resource: 'strength'
    type: 2
    level: 4.6
    utility:
      feature: 5.4
  feature5:
    resource: 'mobile'
    type: 0
    utility:
      feature: 9.7
  feature6:
    resource: 'holonomic'
    type: 0
    utility:
      feature: 10.0
