type: 'robot'
utility:
  expression: 'skill distance'
  distance: 0.6
skills:
  size: 4
  skill0:
    resource: 'camera'
    type: 0
    utility:
      skill: 3.6
  skill1:
    resource: 'processor'
    type: 1
    level: 2
    utility:
      skill: 5.0
  skill2:
    resource: 'battery'
    type: 2
    level: 0.94
    utility:
      skill: 1.1
  skill3:
    resource: 'strengh'
    type: 2
    level: 3.4
    utility:
      skill: 7.5
  skill4:
    resource: 'mobile'
    type: 0
    utility:
      skill: 3.0
