type: 'robot'
queue_size: 10
max_size: 2
utility:
  expression: 'distance feature'
  distance: 0.4
features:
  size: 7
  feature0:
    resource: 'camera'
    type: 0
    utility:
      feature: 0.4
  feature1:
    resource: 'battery'
    type: 2
    level: 0.7
    utility:
      feature: 1.8
  feature2:
    resource: 'processor'
    type: 1
    level: 3
    utility:
      feature: 3.2
  feature3:
    resource: 'laserscan'
    type: 0
    utility:
      feature: 0.9
  feature4:
    resource: 'strength'
    type: 2
    level: 6.6
    utility:
      feature: 3.4
  feature5:
    resource: 'mobile'
    type: 0
    utility:
      feature: 2.8
  feature6:
    resource: 'holonomic'
    type: 0
    utility:
      feature: 20.0
