type: 'robot'
utility:
  expression: 'distance skill'
  distance: 0.3
skills:
  size: 7
  skill0:
    resource: 'camera'
    type: 0
    utility:
      skill: 5.0
  skill1:
    resource: 'battery'
    type: 2
    level: 0.85
    utility:
      skill: 1.0
  skill2:
    resource: 'processor'
    type: 1
    level: 1
    utility:
      skill: 7.0
  skill3:
    resource: 'laserscan'
    type: 0
    utility:
      skill: 0.4
  skill4:
    resource: 'strengh'
    type: 2
    level: 4.6
    utility:
      skill: 5.4
  skill5:
    resource: 'mobile'
    type: 0
    utility:
      skill: 9.7
  skill6:
    resource: 'holonomic'
    type: 0
    utility:
      skill: 10.0
