type: 'robot'
queue_size: 10
max_size: 2
utility:
  expression: 'distance feature'
  distance: 0.45
features:
  size: 4
  feature0:
    resource: 'strength'
    type: 2
    level: 0.6
    utility:
      feature: 4.2
  feature1:
    resource: 'battery'
    type: 2
    level: 0.85
    utility:
      feature: 1.2
  feature2:
    resource: 'processor'
    type: 1
    level: 1
    utility:
      feature: 1.4
  feature3:
    resource: 'mobile'
    type: 0
    utility:
      feature: 1.5
