type: 'robot'
utility:
  expression: 'distance skill'
  distance: 0.45
skills:
  size: 4
  skill0:
    resource: 'strengh'
    type: 2
    level: 0.6
    utility:
      skill: 4.2
  skill1:
    resource: 'battery'
    type: 2
    level: 0.85
    utility:
      skill: 1.2
  skill2:
    resource: 'processor'
    type: 1
    level: 1
    utility:
      skill: 1.4
  skill3:
    resource: 'mobile'
    type: 0
    utility:
      skill: 1.5
